---
# tasks file for ansible-role-squid

- name: "Install required packages on redhat"
  yum: 
    name: 
      - policycoreutils-python
      - iproute
    state: "{{ squid_package_state }}"

- name: "Set up extra cache dir"
  file:
    path: '{{ squid_cache_dir2["path"] }}'
    state: directory
    owner: squid
    group: squid
    mode: 0755
  when: squid_extra_cache_dir

- name: "SELinux: Allow squid to use SNMP UDP port"
  seport:
    ports: 161
    proto: "udp"
    setype: "squid_port_t"
    state: present
  when: 
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: "SELinux: Allow squid to use extra cache dir (1/2)"
  command: /usr/sbin/semanage fcontext -a -t squid_cache_t '{{ squid_cache_dir2["path"]}}(/.*?)'
  when:
    - squid_extra_cache_dir is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: "SELinux: Allow squid to use extra cache dir (2/2)"
  command: /usr/sbin/semanage fcontext -a -t squid_cache_t '{{ squid_cache_dir2["path"]}}'
  when:
    - squid_extra_cache_dir is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: "SELinux: Set correct context for extra cache dir"
  command: restorecon -R {{ squid_cache_dir2["path"] }}
  when:
    - squid_extra_cache_dir is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: "Template in squid.conf"
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: squid
    mode: 0640
    backup: yes
  notify:
   - restart squid

- name: "Start and enable squid"
  service:
    name: squid
    state: started
    enabled: yes
...
