---
# tasks file for ansible-role-squid

- name: "Install squid"
  yum: name=squid state=latest

- name: "Install policycoreutils-python"
  yum: name=policycoreutils-python state=latest
  when: squid_extra_cache_dir

- name: "Install ss from package iproute"
  yum: name=iproute state=latest

- name: "Set up extra cache dir"
  file: path={{ squid_cache_dir2["path"] }} state=directory owner=squid group=squid mode=0755
  when: squid_extra_cache_dir

- name: "SELinux: Allow squid to use SNMP UDP port"
  seport:
        ports: 161
        proto: "udp"
        setype: "squid_port_t"
        state: present

- name: "SELinux: Allow squid to use extra cache dir"
  command: /usr/sbin/semanage fcontext -a -t squid_cache_t '{{ squid_cache_dir2["path"]}}(/.*?)'
  command: /usr/sbin/semanage fcontext -a -t squid_cache_t '{{ squid_cache_dir2["path"]}}'
  when: squid_extra_cache_dir

- name: "SELinux: Set correct context for extra cache dir"
  command: restorecon -R {{ squid_cache_dir2["path"] }} 
  when: squid_extra_cache_dir

- name: "Template in squid.conf"
  template: src=squid.conf.j2 dest=/etc/squid/squid.conf owner=root group=squid mode=0640 backup=yes
  notify:
   - restart squid

- name: "Start and enable squid"
  service: name=squid state=started enabled=yes

- name: "is squid listening?"
  command: ss -lntu
  register: squid_ss_output
  check_mode: no
  changed_when: False

- debug: var=squid_ss_output verbosity=1

- name: Wait for squid port to come up
  wait_for: port=3128 timeout=60 host=0.0.0.0
  when: ansible_virtualization_type != "docker"

